---
title: "Research"
---

## Publications

Martin, Matthew. "Elite Fractures, Public Capture: The Strategic Use of Public Consultation in Global Constitution-Making." *Journal of Law and Courts* (forthcoming).

Cruz, Andrés, Zachary Elkins, Roy Gardner, Matthew Martin, and Ashley Moran. 2023. "Measuring Constitutional Preferences: A New Method for Analyzing Public Consultation Data." *PLOS ONE* 18 (12). [`https://doi.org/10.1371/journal.pone.0295396`](https://doi.org/10.1371/journal.pone.0295396)

## Works in progress

Martin, Matthew. "Product of the Process: Public Consultation in Global Constitution-Making."

Martin, Matthew. "Deportation by Design: How Political Entrepreneurs Engineered Crime-Based Deportation in the United States."

Cruz, Andrés, Elkins, Zachary, Roy Gardner, Matthew Martin, Ashley Moran, Guillermo Pérez. "Did the Pendulum Swing and Who Controlled It? Tracing Constitutional Ideas across Three Phases of Consultation, Deliberation, and Constitution Drafting in Chile"

Gardner, Roy, Matthew Martin, Zachary Elkins, Ashley Moran, Guillermo Pérez. "Expanding Your Vocabulary: Topic Integration Using the Segments-as-Topics (SAT) Approach."

## Other works

Elkins, Zachary, Matthew Martin, Ashley Moran, Guillermo Pérez. 2023. "[12 Core Attributes of the Chilean Constitutional Proposal](https://www.constituteproject.org/data-stories/chile-2023-proposal)." Constitute Project.

Martin, Matthew and Guillermo Pérez. "[Chile 2023 - Draft of 30 Oct 2023](https://www.constituteproject.org/constitution/Chile_2023DD)." Translation of Chilean constitutional proposal. Constitute Project.
