---
title: "Teaching"
---

## Courses

### GOV 357L Judicial Process and Behavior

-   Served as instructor for an upper-level undergraduate course.

### UT Government Department Methods Camp

-   Co-organized an introduction to methods for political science for incoming graduate students during the summers of 2022 and 2023 with Andrés Cruz.
-   See our website [here](https://methodscamp.github.io/).

## Positions

### Methods Fellow

-   Assist graduate students in the Department of Government with methods-related questions, organize methods workshops, and coordinate weekly co-working hours.

-   Fall 2023, Spring 2024

## Teaching Assistantships

### UGS 303: Drugs, Commerce, and Immigration in U.S.-Mexico Relations

-   Dr. Kenneth Greene
-   Fall 2023, Spring 2022

### GOV 391L: Statistical Analysis in Political Science II

-   Dr. Alison Craig
-   Spring 2023

### GOV 391J: Statistical Analysis in Political Science I

-   Dr. Kenneth Greene
-   Fall 2023, Spring 2022

### GOV 320N: Civil Rights and Civil Liberties

-   Dr. Alan Sager
-   Fall 2021

### GOV S365W: Human Rights and World Politics

-   Dr. Rhonda Evans
-   Summer 2021

### GOV 312L: The U.S. in Comparative Perspective

-   Dr. Kurt Weyland
-   Spring 2021

### GOV 328L: Introduction to Latin American Politics

-   Dr. Raul Madrid
-   Fall 2020
