---
title: "Research"
listing:
  - id: articles
    contents: "articles/*/index.qmd"
    sort: "date desc"
    template: ../html/research/listing.ejs
    categories: true
  - id: working-papers
    contents: "working-papers/*/index.qmd"
    sort: "date desc"
    template: ../html/research/listing.ejs
  - id: translations
    contents: "translations/*/index.qmd"
    sort: "date desc"
    template: ../html/research/listing.ejs
page-layout: full
include-back-link: false
toc-location: right
aliases: 
  - research.html
---

My research focuses on global constitution-making, with a particular interest in mechanisms of public consultation. My other areas of specialization include Latin American politics, statistical methods, and natural language processing. {{< ai blank-just-to-add-ai-dependency-to-this-page >}} 

## Journal articles

::: {#articles}
:::

## Working papers

::: {#working-papers}
:::

## Translations

::: {#translations}
:::

## Publications

Martin, Matthew. "Elite Fractures, Public Capture: The Strategic Use of Public Consultation in Global Constitution-Making." *Journal of Law and Courts* (forthcoming). [\[PDF\]](files/EFPC_final.pdf)

## Working papers

Martin, Matthew. "Deportation by Design: How Political Entrepreneurs Engineered Crime-Based Deportation in the United States."

## Works in progress

Martin, Matthew. "Product of the Process: Public Consultation in Global Constitution-Making."

Cruz, Andrés, Elkins, Zachary, Roy Gardner, Matthew Martin, Ashley Moran, Guillermo Pérez. "Tracing the Expression and Uptake of Constitutional Ideas across Three Reform Efforts in Chile."

Gardner, Roy, Matthew Martin, Zachary Elkins, Ashley Moran, Guillermo Pérez. "Expanding Your Vocabulary: Topic Integration Using the Segments-as-Topics (SAT) Approach."

## Other works

Elkins, Zachary, Matthew Martin, Ashley Moran, Guillermo Pérez. 2023. "[12 Core Attributes of the Chilean Constitutional Proposal](https://www.constituteproject.org/data-stories/chile-2023-proposal)." Constitute Project.

Martin, Matthew and Guillermo Pérez. "[Chile 2023 - Draft of 30 Oct 2023](https://www.constituteproject.org/constitution/Chile_2023DD)." Translation of Chilean constitutional proposal. Constitute Project.
