---
title: "Expanding Your Vocabulary: Topic Integration Using the Segments-as-Topics (SAT) Approach"
date: 2024-09-01
author:
  - name: Roy Gardner
    affiliation: Comparative Constitutions Project, University of Texas at Austin
  - name: Matthew Martin
    url: https://mattjamesmartin.github.io/
    orcid: 0000-0003-3460-3603
    affiliation: Department of Government, University of Texas at Austin
  - name: Andrés Cruz
    url: https://arcruz0.github.io/
    orcid: 0000-0003-3819-9433
    affiliation: Department of Government, University of Texas at Austin
  - name: Zachary Elkins
    url: https://sites.google.com/site/zachelkinstexas/
    orcid: 0000-0002-7932-773X
    affiliation: Department of Government, University of Texas at Austin
  - name: Ashley Moran
    url: https://liberalarts.utexas.edu/government/faculty/am49396
    orcid: 0000-0001-5969-2134
    affiliation: Department of Government, University of Texas at Austin
categories: 
  - Constitutional design
pub-info:
  reference: >-
    Roy Gardner, <strong>Matthew Martin</strong>, <a href="https://arcruz0.github.io/">Andrés Cruz</a>, <a href="https://site.google.com/site/zachelkinstexas/">Zachary Elkins</a>, and <a href="https://liberalarts.utexas.edu/government/faculty/am49396">Ashley Moran</a>. “Expanding Your Vocabulary: Topic Integration Using the Segments-as-Topics (SAT) Approach.”
  links:
  - name: Draft
    url: gardner-expanding.pdf
    local: true
    icon: fa-solid fa-file-pdf
---

## Abstract

Topic discovery and integration are essential to maintain vocabularies—the set of concepts underlying a textual corpus. We present a three-stage methodology combining automation and human expertise to assess candidate topics, which we call the segments-as-topic (SAT) approach. To develop the methodology, we use a vocabulary created by the Comparative Constitutions Project (CCP) that tracks more than 330 topics in a corpus of national constitutions. In the (1) SAT generation stage, we formulate topics that are distinct from existing topics, then use a sentence-level semantic similarity model to search for constitution sections (segments) that are similar in meaning to each topic. Domain experts collaborate on the formulation of the topic text until a formulation is identified that produces a set of search results that match the intent of the topic. Once a sufficient number of constitution sections have been matched, the (2) topic expansion stage of the methodology uses the sections themselves to find additional semantically similar sections. These sections are assessed and are either added to the section set or rejected. The process is repeated until no further new sections are found at which point the section set constitutes the definitive set of sections for the topic. Finally, in the (3) validation stage, a panel of scholars decides whether to accept the topic into the CCP vocabulary, after which matching constitution sections are automatically tagged with the topic. Several new topics have been added to the CCP vocabulary with these methods, some of which we present here to illustrate our process and results. The methodology provides researchers with a systematic way to expand existing vocabularies. {{< fa blank >}} 