---
title: "Measuring constitutional preferences: A new method for analyzing public consultation data"
date: 2023-12-14
author:
  - name: Andrés Cruz
    url: https://arcruz0.github.io/
    orcid: 0000-0003-3819-9433
    affiliation: Department of Government, University of Texas at Austin
  - name: Zachary Elkins
    url: https://sites.google.com/site/zachelkinstexas/
    orcid: 0000-0002-7932-773X
    affiliation: Department of Government, University of Texas at Austin
  - name: Roy Gardner
    affiliation: Comparative Constitutions Project, University of Texas at Austin
  - name: Matthew Martin
    url: https://mattjamesmartin.github.io/
    orcid: 0000-0003-3460-3603
    affiliation: Department of Government, University of Texas at Austin
  - name: Ashley Moran
    url: https://liberalarts.utexas.edu/government/faculty/am49396
    orcid: 0000-0001-5969-2134
    affiliation: Department of Government, University of Texas at Austin
categories: 
  - Constitutional design
  - Public consultation 
  - Natural language processing
  - Chile
  - Latin America
pub-info:
  reference: >-
    <a href="https://arcruz0.github.io/">Andrés Cruz</a>, <a href="https://site.google.com/site/zachelkinstexas/">Zachary Elkins</a>, Roy Gardner, <strong>Matthew Martin</strong>, and <a href="https://liberalarts.utexas.edu/government/faculty/am49396">Ashley Moran</a>. “Measuring constitutional preferences: A new method for analyzing public consultation data,” <em>PLoS ONE</em> 18, no. 12 (2023): e0295396, doi: <a href="https://doi.org/10.1371/journal.pone.0295396"><code>10.1371/journal.pone.0295396</code></a>
  links:
  - name: Final version
    url: https://doi.org/10.1371/journal.pone.0295396
    icon: fa-solid fa-scroll
  - name: Code/data
    url: https://zenodo.org/records/10206770
    icon: fa-solid fa-database
  - name: Add to Zotero
    url: https://www.zotero.org/save?type=doi&q=10.1371/journal.pone.0295396
    icon: ai ai-zotero
doi: 10.1371/journal.pone.0295396
---

## Abstract

Public consultation has become an indispensable part of constitutional design, yet the voluminous, narrative data produced are often impractical to analyze. There are also few, if any, standards for such analysis. Using a comprehensive reference ontology from the Comparative Constitutions Project (CCP), we develop a new methodology to identify constitutional topics of most concern to citizens and compare these to topics in constitutions globally. We analyze data from Chile’s 2016 public consultations—an ambitious process that produced nearly 265,000 narrative responses and launched the constitutional reform process that remains underway today. We leverage advances in natural language processing, in particular sentence-level semantic similarity technology, to classify consultation responses with respect to constitutional topics. Our methodology has potential for advocates, drafters, and researchers seeking to analyze public consultation data that too often go unexamined. {{< fa blank >}} 

## Citation

<p class="buttons" style="text-align:center;">

<a class="btn btn-danger" target="_blank"             href="https://www.zotero.org/save?type=doi&q=10.1371/journal.pone.0295396">{{< ai zotero >}} Add to Zotero {{< fa square-arrow-up-right >}} </a>

</p>

``` bibtex
@article{cruz2023measuring,
  title={Measuring constitutional preferences: A new method for analyzing public consultation data},
  author={Cruz, Andr{\'e}s and Elkins, Zachary and Gardner, Roy and Martin, Matthew and Moran, Ashley},
  journal={Plos one},
  volume={18},
  number={12},
  pages={e0295396},
  year={2023},
  doi = {10.1371/journal.pone.0295396}
}
```
